version: '3.8'

services:
  postgres:
    image: postgres:latest # Utiliser une image PostgreSQL
    container_name: edenmind-postgres
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak 
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - edenmind-network
    ports: 
      - "5432:5432" 

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: edenmind-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      
      KC_DB: postgres 
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db?sslmode=disable
      KC_DB_USERNAME: keycloak 
      KC_DB_PASSWORD: password 
      
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
    
    command: start-dev
    
    ports:
      - "8086:8080"
    
    networks:
      - edenmind-network
    
    depends_on:
      - postgres 
    
networks:
  edenmind-network:
    driver: bridge

volumes:
  postgres_data: