name: eden_mind_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^6.1.0
  flutter_appauth: ^11.0.0
  flutter_secure_storage: ^10.0.0
  http: ^1.1.0
  provider: ^6.0.0
  jwt_decoder: ^2.0.1
  image_picker: ^1.0.7
  audioplayers: ^6.5.1
  flutter_markdown_plus: 1.0.5
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  image: ^4.1.7
  camera: ^0.10.6
  tflite_flutter: ^0.12.1
  google_mlkit_face_detection: ^0.13.1
  permission_handler: ^12.0.1
  universal_html: ^2.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
